const LOGIN = 'LOGIN';
const FAVORITAR = 'FAVORITAR';
const DESFAVORITAR = 'DESFAVORITAR';
const CARREGAR_ANIMAIS = 'CARREGAR_ANIMAIS';
const SET_LOADING = 'SET_LOADING';

export {FAVORITAR, DESFAVORITAR, CARREGAR_ANIMAIS, LOGIN, SET_LOADING};
